[application]
name = "portfolio"
default_platform = "web"

[web.app]
# HTML title tag content
title = "portfolio"

[web.resource]
# Asset directory configuration
dir = ["assets"]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
